create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  brand text not null,
  service text not null,
  city text not null,
  source_url text,
  name text not null,
  phone text not null,
  message text,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

revoke all on public.leads from anon, authenticated;
