-- MHS Network: content tree + lead capture.
-- Content is world-readable; writes are service-role only (the admin app uses
-- the service key behind an authenticated server route).

create table if not exists public.brands (
  key           text primary key,
  name          text not null,
  domain        text not null,
  phone         text not null,
  accent        text not null default '#2563c9',
  central       boolean not null default false,
  tagline       text not null default '',
  pattern       text not null default 'service_city'
                check (pattern in ('service_city','service_niche_city')),
  network_name  text not null default 'The MHS Network',
  ga4_id        text not null default '',
  position      int  not null default 0,
  created_at    timestamptz not null default now()
);

create table if not exists public.services (
  id         bigint generated by default as identity primary key,
  brand_key  text not null references public.brands(key) on delete cascade,
  slug       text not null,
  name       text not null,
  short      text not null default '',
  hero       text not null default '',
  intro      text not null default '',
  "includes" jsonb not null default '[]'::jsonb,
  why        text not null default '',
  "from"     text not null default 'quote',
  faqs       jsonb not null default '[]'::jsonb,
  position   int  not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_key, slug)
);

create table if not exists public.cities (
  id         bigint generated by default as identity primary key,
  brand_key  text not null references public.brands(key) on delete cascade,
  slug       text not null,
  name       text not null,
  region     text not null default '',
  tier       text not null default '',
  known_for  text not null default '',
  note       text,
  position   int  not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_key, slug)
);

create table if not exists public.niches (
  id         bigint generated by default as identity primary key,
  brand_key  text not null references public.brands(key) on delete cascade,
  slug       text not null,
  name       text not null,
  line       text not null default '',
  position   int  not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_key, slug)
);

create table if not exists public.leads (
  id         bigint generated by default as identity primary key,
  brand      text not null,
  service    text not null,
  city       text not null,
  source_url text,
  name       text not null,
  phone      text not null,
  message    text,
  status     text not null default 'new'
             check (status in ('new','contacted','qualified','won','lost')),
  created_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_idx     on public.leads (status);
create index if not exists services_brand_idx   on public.services (brand_key, position);
create index if not exists cities_brand_idx     on public.cities (brand_key, position);
create index if not exists niches_brand_idx     on public.niches (brand_key, position);

alter table public.brands   enable row level security;
alter table public.services enable row level security;
alter table public.cities   enable row level security;
alter table public.niches   enable row level security;
alter table public.leads    enable row level security;

-- Content is public to read.
drop policy if exists "content readable" on public.brands;
create policy "content readable" on public.brands   for select using (true);
drop policy if exists "content readable" on public.services;
create policy "content readable" on public.services for select using (true);
drop policy if exists "content readable" on public.cities;
create policy "content readable" on public.cities   for select using (true);
drop policy if exists "content readable" on public.niches;
create policy "content readable" on public.niches   for select using (true);

-- Leads are write-only from the public side and never readable by anon:
-- no select policy, and inserts go through the server with the service key.
revoke all on public.leads from anon, authenticated;
