-- MHS Network content tree + lead capture.
--
-- Hosted alongside another app, so every object is prefixed mhs_ and nothing
-- here touches existing tables.
--
-- Security model, which is why there is no service-role key in this app:
--   * content tables  : anyone may read, only signed-in staff may write.
--   * mhs_leads       : anonymous visitors can neither read nor write it.
--                       The public form goes through mhs_submit_lead(), a
--                       SECURITY DEFINER function that validates and inserts,
--                       so a lead can be created but never listed or altered
--                       without a session.

create table if not exists public.mhs_brands (
  key           text primary key,
  name          text not null,
  domain        text not null,
  phone         text not null,
  accent        text not null default '#2563c9',
  central       boolean not null default false,
  tagline       text not null default '',
  pattern       text not null default 'service_city'
                check (pattern in ('service_city','service_niche_city')),
  network_name  text not null default 'The MHS Network',
  ga4_id        text not null default '',
  position      int  not null default 0,
  created_at    timestamptz not null default now()
);

create table if not exists public.mhs_services (
  id         bigint generated by default as identity primary key,
  brand_key  text not null references public.mhs_brands(key) on delete cascade,
  slug       text not null,
  name       text not null,
  short      text not null default '',
  hero       text not null default '',
  intro      text not null default '',
  "includes" jsonb not null default '[]'::jsonb,
  why        text not null default '',
  "from"     text not null default 'quote',
  faqs       jsonb not null default '[]'::jsonb,
  position   int  not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_key, slug)
);

create table if not exists public.mhs_cities (
  id         bigint generated by default as identity primary key,
  brand_key  text not null references public.mhs_brands(key) on delete cascade,
  slug       text not null,
  name       text not null,
  region     text not null default '',
  tier       text not null default '',
  known_for  text not null default '',
  note       text,
  position   int  not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_key, slug)
);

create table if not exists public.mhs_niches (
  id         bigint generated by default as identity primary key,
  brand_key  text not null references public.mhs_brands(key) on delete cascade,
  slug       text not null,
  name       text not null,
  line       text not null default '',
  position   int  not null default 0,
  created_at timestamptz not null default now(),
  unique (brand_key, slug)
);

create table if not exists public.mhs_leads (
  id         bigint generated by default as identity primary key,
  brand      text not null check (length(brand)   between 1 and 120),
  service    text not null check (length(service) between 1 and 160),
  city       text not null check (length(city)    between 1 and 120),
  source_url text          check (source_url is null or length(source_url) <= 500),
  name       text not null check (length(name)    between 1 and 120),
  phone      text not null check (length(phone)   between 7 and 32),
  message    text          check (message is null or length(message) <= 2000),
  status     text not null default 'new'
             check (status in ('new','contacted','qualified','won','lost')),
  created_at timestamptz not null default now()
);

create index if not exists mhs_leads_created_idx   on public.mhs_leads (created_at desc);
create index if not exists mhs_leads_status_idx    on public.mhs_leads (status);
create index if not exists mhs_services_brand_idx  on public.mhs_services (brand_key, position);
create index if not exists mhs_cities_brand_idx    on public.mhs_cities (brand_key, position);
create index if not exists mhs_niches_brand_idx    on public.mhs_niches (brand_key, position);

alter table public.mhs_brands   enable row level security;
alter table public.mhs_services enable row level security;
alter table public.mhs_cities   enable row level security;
alter table public.mhs_niches   enable row level security;
alter table public.mhs_leads    enable row level security;

-- ---------- content: world readable, staff writable ----------
do $$
declare t text;
begin
  foreach t in array array['mhs_brands','mhs_services','mhs_cities','mhs_niches'] loop
    execute format('drop policy if exists "read" on public.%I', t);
    execute format('create policy "read" on public.%I for select using (true)', t);

    execute format('drop policy if exists "staff write" on public.%I', t);
    execute format($f$create policy "staff write" on public.%I
                     for all to authenticated using (true) with check (true)$f$, t);
  end loop;
end $$;

-- ---------- leads: only a signed-in session sees them ----------
drop policy if exists "staff read leads" on public.mhs_leads;
create policy "staff read leads" on public.mhs_leads
  for all to authenticated using (true) with check (true);

-- Anonymous visitors get no table rights at all.
revoke all on public.mhs_leads from anon;

-- ---------- the only way the public form writes ----------
create or replace function public.mhs_submit_lead(
  p_brand      text,
  p_service    text,
  p_city       text,
  p_name       text,
  p_phone      text,
  p_message    text default null,
  p_source_url text default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_digits text := regexp_replace(coalesce(p_phone,''), '\D', '', 'g');
begin
  if coalesce(btrim(p_name),'') = '' or coalesce(btrim(p_brand),'') = ''
     or coalesce(btrim(p_service),'') = '' or coalesce(btrim(p_city),'') = '' then
    raise exception 'missing required field';
  end if;

  if length(v_digits) < 7 or length(v_digits) > 15 then
    raise exception 'invalid phone';
  end if;

  insert into public.mhs_leads (brand, service, city, name, phone, message, source_url)
  values (
    left(btrim(p_brand), 120),
    left(btrim(p_service), 160),
    left(btrim(p_city), 120),
    left(btrim(p_name), 120),
    left(btrim(p_phone), 32),
    nullif(left(btrim(coalesce(p_message,'')), 2000), ''),
    nullif(left(btrim(coalesce(p_source_url,'')), 500), '')
  );
end $$;

revoke all on function public.mhs_submit_lead(text,text,text,text,text,text,text) from public;
grant execute on function public.mhs_submit_lead(text,text,text,text,text,text,text)
  to anon, authenticated;
